openapi: 3.0.3
info:
  title: MoviesApi
  description: omdbapi.com
  version: 1.0.0
servers:
  - url: https://www.omdbapi.com
tags:
  - name: moviesList
    description: Movies list
  - name: movieDetails
    description: Movie details
paths:
  /?s:
    get:
      tags:
        - moviesSearch
      operationId: getMovies
      summary: Movies list
      parameters:
        - name: s
          in: query
          description: Title of movie or series
          required: true
          schema:
            type: string
        - name: apiKey
          in: query
          description: Your API Key
          required: true
          schema:
            type: string
        - name: type
          in: query
          description: Return movie, series or episode
          required: false
          schema:
            type: string
            enum: [movies, series, episode]
        - name: page
          in: query
          description: Page number to return
          required: false
          schema:
            type: integer
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MoviesResponse'
        default:
          description: enexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
  /?i:
    get:
      tags:
        - movieDetails
      operationId: getMovieDetails
      summary: Movie details
      parameters:
        - name: i
          in: query
          description: A valid IMDb ID
          required: true
          schema:
            type: string
        - name: apiKey
          in: query
          description: Your API Key
          required: true
          schema:
            type: string
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovieFull'
        default:
          description: enexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
components:
  schemas:
    MoviesResponse:
      type: object
      required:
        - Response
      properties:
        totalResults: 
          type: string
        Response: 
          type: string
        Search: 
          type: array
          items: 
            $ref: '#/components/schemas/MovieShort'
    MovieShort:
      type: object
      required:
        - imdbID
      properties:
        Title: 
          type: string
        Year: 
          type: string
        imdbID: 
          type: string
        Type: 
          type: string
        Poster: 
          type: string
    MovieFull:
      type: object
      required:
        - imdbID
        - Title
      properties:
        Title: 
          type: string
        Year: 
          type: string
        Rated: 
          type: string
        Released: 
          type: string
        Runtime: 
          type: string
        Genre: 
          type: string
        Director: 
          type: string
        Writer: 
          type: string
        Actors: 
          type: string
        Plot: 
          type: string
        Language: 
          type: string
        Country: 
          type: string
        Awards: 
          type: string
        Poster: 
          type: string
        Ratings: 
          type: array
          items:
            $ref: '#/components/schemas/MovieRating'
        Metascore: 
          type: string
        imdbRating: 
          type: string
        imdbVotes: 
          type: string
        imdbID: 
          type: string
        Type: 
          type: string
        DVD: 
          type: string
        BoxOffice: 
          type: string
        Production: 
          type: string
        Website: 
          type: string
        Response: 
          type: string
    MovieRating:
      required:
      - Source
      - Value
      type: object
      properties:
        Source: 
          type: string
        Value: 
          type: string
    ErrorModel:
      required:
      - code
      - message
      type: object
      properties:
        Response:
          type: string
        Error:
          type: string
